name: example
description: Positioned tap detector example.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  positioned_tap_detector_2:
    path: ../

flutter:
  uses-material-design: true
